[package]
authors = ["Naoki Kaneko <puripuri2100@gmail.com>"]
edition = "2018"
name = "mdbook-satysfi"
version = "0.0.1-beta"
license = "MIT"

[dependencies]
mdbook = "0.4.4"
pulldown-cmark = "0.8.0"
regex = "1.4.2"
html_parser = "0.6.2"
toml = "0.5.8"
