name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: amutake/satysfi:0.0.6
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.12'

      - run: cargo install mdbook-satysfi

      - run: |
          export HOME=/root # workaround
          eval $(opam env)
          opam update
          opam install satysfi-class-mdbook-satysfi
          satyrographos install
          
      - run: |
          cd $(pwd)/doc/ja
          mdbook build

      - run: |
          satysfi $(pwd)/doc/ja/book/satysfi/main.saty -o $(pwd)/doc/ja/book/satysfi/ja.pdf

      - run: |
          mkdir -p pages/ja
          cp -r -f doc/ja/book/html/* pages/ja
          cp -f doc/ja/book/satysfi/ja.pdf pages/ja

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pages
